name: JMeter Performance Test Execution

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  load_test_run:
    runs-on: ubuntu-latest
    
    env:
      JMX_FILE: patanjali_SamplePlan.jmx
      RESULTS_DIR: jmeter-results
      TARGET_BRANCH: main   # Or a dedicated branch like 'Dinesh'
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Results Directory
        run: mkdir -p ${{ env.RESULTS_DIR }}

      - name: Run JMeter Test
        uses: QAInsights/PerfAction@v5.6.3
        with:
          test-plan-path: ${{ env.JMX_FILE }}
          args: "-e -o reports"

      - name: Store Reports in Repository
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          mkdir -p performance-reports

          # Remove old reports
          rm -rf performance-reports/*

          # Copy new reports
          cp -r reports/* performance-reports/
          cp result.jtl performance-reports/

          git add performance-reports/*
          git commit -m "Add latest JMeter performance reports"
          git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }} ${{ env.TARGET_BRANCH }} --force
