name: JMeter Performance Test Execution

on:
  # Allows manual running from the GitHub Actions UI
  workflow_dispatch:
  # Runs on every push to the main branch
  push:
    branches: [ main ]
  # Runs every day at 01:00 AM UTC
  schedule:
    - cron: '0 1 * * *'

jobs:
  load_test_run:
    runs-on: ubuntu-latest
    
    env:
      JMX_FILE: patanjali_SamplePlan.jmx
      RESULTS_DIR: jmeter-results
      
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Create results directory
      - name: Create Results Directory
        run: mkdir -p ${{ env.RESULTS_DIR }}

      # Step 3: Run JMeter performance test using PerfAction
      - name: Run JMeter Test
        uses: QAInsights/PerfAction@v5.6.3
        with:
          test-plan-path: ${{ env.JMX_FILE }}
          results-file: ${{ env.RESULTS_DIR }}/result.jtl
          args: "-n -t ${{ env.JMX_FILE }} -l ${{ env.RESULTS_DIR }}/result.jtl -e -o ${{ env.RESULTS_DIR }}/html-report"

      # Step 4: Upload test results and HTML report as artifacts
      - name: Upload Test Results Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.JMX_FILE }}-performance-report
          path: ${{ env.RESULTS_DIR }}/
          retention-days: 7
