name: JMeter Performance Test Execution

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 1 * * *'

jobs:
  load_test_run:
    runs-on: ubuntu-latest
    
    env:
      JMX_FILE: patanjali_SamplePlan.jmx
      RESULTS_DIR: jmeter-results
      TARGET_BRANCH: Dinesh
      
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Create results directory
      - name: Create Results Directory
        run: mkdir -p ${{ env.RESULTS_DIR }}

      # Step 3: Run JMeter performance test using PerfAction
      - name: Run JMeter Test
        uses: QAInsights/PerfAction@v5.6.3
        with:
          test-plan-path: ${{ env.JMX_FILE }}
          args: "-e -o reports"

      # Step 4: Upload test results and HTML report as artifacts
      - name: Upload Test Results Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.JMX_FILE }}-performance-report
          path: result.jtl
          retention-days: 7

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-html-reports
          path: reports
          if-no-files-found: error

      # Step 5: Push HTML report to another branch
      - name: Commit and Push HTML Reports to Branch Dinesh
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Checkout the target branch (create if it doesn't exist)
          git fetch origin ${{ env.TARGET_BRANCH }}
          git checkout -B ${{ env.TARGET_BRANCH }}

          # Copy reports into branch
          cp -r reports/* .

          # Add, commit, and push
          git add .
          git commit -m "Update JMeter HTML reports from workflow run"
          git push origin ${{ env.TARGET_BRANCH }} --force
